apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: "14.12.3"
    helm:
      parameters:
        - name: auth.rootPassword
          value: "root"
        - name: architecture
          value: "standalone"
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
