# This Docker Compose has 3 services.
# The app is built using the Dockerfile that builds the app itself and the data that is inserted.
# MongoDB image for the database.
# The Tests that are built from Dockerfile.testing and always use the new pushed code for the testing.
# The only thing that is manual is the tests, which need to be updated for the new features that are added to the code.

version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/MyDataBase
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    environment:
      - MONGODB_URI=mongodb://mongo:27017/MyDataBase
    depends_on:
      - mongo
volumes:
  mongo_data:




