# need to add another container that has the DB creation.

version: '3.8'

services:

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/DataBase
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    environment:
      - MONGODB_URI=mongodb://mongo:27017/DataBase
    depends_on:
      - mongo
      - app
      
volumes:
  mongo_data:




