apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test-container
    image: thebluedrara/wikiapp:2.0
    ports:
    - containerPort: 5000  

  - name: mongodb
    image: mongo:latest 
    ports:
    - containerPort: 27017 
